### ISSUE TITLE
custom items not working properly

### ISSUE THREAD

**Issue by cocount57** [Jsinco/BreweryX#45]
When i set custom items using lore, they work fine. When i set them using name, it does not work at all. 
When i set them using custom model data (that would be the most useful), the plugin can see them, but if i have two items with same material but different CMDs, it seems them all as same item. Like this: 
item A - wheat with cmd 001
item B - wheat with cmd 002
Recipe: brew 3 A
The recipe works with A, but it will also work with B

Would be really cool to have ability to add custom items with NBT tags, or to add NBT tags to brews

**Comment by szarkans** [comment]
Kinda same here.

I can brew `someDrink` with default cod that has no CMD at all.
```yaml
custom-item
  material: cod
  customModelData:
  - 45
  - 46
  - 47

someDrink:
  ingredients:
    - custom-item/1
```
